name = "OpenReality"
uuid = "b08b1914-4d33-46de-8c63-ba029b7f1c5f"
version = "0.1.0"
authors = ["OpenReality Contributors"]

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Quaternions = "94ee1d12-ae83-5a48-8b1c-48b8ff168ae0"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ColorTypes = "0.11, 0.12"
GLFW = "3"
GeometryBasics = "0.4"
ModernGL = "1"
Observables = "0.5"
Quaternions = "0.7.7"
StaticArrays = "1.5"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
